name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go

    - name: Set up SQLite
      run:  sudo apt-get install sqlite3

    - name: Start local MySQL
      run: sudo /etc/init.d/mysql start

    - name: Test source code
      run:  script/test-source

    - name: Test build
      run:  script/test-build

    - name: Test unit
      run:  script/test-unit

    - name: Test integration
      run:  script/test-integration

    - name: Test documentation
      run:  script/test-docs
